import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Sidebar from "../components/layout/Sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-hidden antialiased p-4 bg-[#F6F7F9]`}
      >
        <div className="flex h-screen">
          <div className="fixed left-0 h-full w-64 overflow-y-auto">
            <Sidebar userRole={"admin"} />
          </div>
          <main className="flex-1 ml-64 overflow-y-auto">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
